export const curtainsData = [
  {
    id: Math.random(),
    nameTitle: "Тип штор",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Подъемные" },
      { id: Math.random(), nameFilter: "Раздвижные" },
      { id: Math.random(), nameFilter: "Стационарные" },
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Вид штор",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Австрийские" },
      { id: Math.random(), nameFilter: "Английские" },
      { id: Math.random(), nameFilter: "Витражные" },
      { id: Math.random(), nameFilter: "Императорские" },
      { id: Math.random(), nameFilter: "Итальянские" },
      { id: Math.random(), nameFilter: "Классические" },
      { id: Math.random(), nameFilter: "Нитяные" },
      { id: Math.random(), nameFilter: "Римские" },
      { id: Math.random(), nameFilter: "Скрещенные" },
      { id: Math.random(), nameFilter: "Французкие" },
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Назначение штор",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Для гостиной" },
      { id: Math.random(), nameFilter: "Для детской" },
      { id: Math.random(), nameFilter: "Для коттеджа" },
      { id: Math.random(), nameFilter: "Для кухни" },
      { id: Math.random(), nameFilter: "Для офиса" },
      { id: Math.random(), nameFilter: "Для спальни" },      
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Вид ткани",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Бамбук" },
      { id: Math.random(), nameFilter: "Бархат" },
      { id: Math.random(), nameFilter: "Батист" },
      { id: Math.random(), nameFilter: "Блэкаут" },
      { id: Math.random(), nameFilter: "Бриллиант" },
      { id: Math.random(), nameFilter: "Вуаль" },
      { id: Math.random(), nameFilter: "Гобелен" },
      { id: Math.random(), nameFilter: "Жаккард" },
      { id: Math.random(), nameFilter: "Канвас" },
      { id: Math.random(), nameFilter: "Кристалон" },
      { id: Math.random(), nameFilter: "Лен" },
      { id: Math.random(), nameFilter: "Лен искусственный" },
      { id: Math.random(), nameFilter: "Микровуаль" },
      { id: Math.random(), nameFilter: "Органза" },
      { id: Math.random(), nameFilter: "Паутинка" },
      { id: Math.random(), nameFilter: "ПЭ 100%" },
      { id: Math.random(), nameFilter: "Рогожа" },
      { id: Math.random(), nameFilter: "Сатен" },
      { id: Math.random(), nameFilter: "Софт" },
      { id: Math.random(), nameFilter: "Сетка" },
      { id: Math.random(), nameFilter: "Тафта" },
      { id: Math.random(), nameFilter: "Шелк" },
    ],
  },  
  {
    id: Math.random(),
    nameTitle: "Состав ткани",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Вискоза" },
      { id: Math.random(), nameFilter: "Лен" },
      { id: Math.random(), nameFilter: "Нейлон" },
      { id: Math.random(), nameFilter: "ПЭ 100%" },
      { id: Math.random(), nameFilter: "Хлопок" },            
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Плотность ткани",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Плотная" },
      { id: Math.random(), nameFilter: "Неплотная" },                  
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Защита от солнца",
    itemsFilter: [
      { id: Math.random(), nameFilter: "более 50%" },
      { id: Math.random(), nameFilter: "менее 50%" },                  
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Высота",
    itemsFilter: [
      { id: Math.random(), nameFilter: "до 200 см" },
      { id: Math.random(), nameFilter: "200-250 см" },                  
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Ширина",
    itemsFilter: [
      { id: Math.random(), nameFilter: "до 150 см" },
      { id: Math.random(), nameFilter: "150-180 см" },
      { id: Math.random(), nameFilter: "200-220 см" },
      { id: Math.random(), nameFilter: "240-300 см" },
      { id: Math.random(), nameFilter: "300-400 см" },
      { id: Math.random(), nameFilter: "400-500 см" },
      { id: Math.random(), nameFilter: "500-600 см" },          
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Дизайн",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Однотонные" },
      { id: Math.random(), nameFilter: "Рисунок" },
      { id: Math.random(), nameFilter: "Вышивка" },        
    ],
  },
  {
    id: Math.random(),
    nameTitle: "Крепление к карнизу",
    itemsFilter: [
      { id: Math.random(), nameFilter: "Зажимы" },
      { id: Math.random(), nameFilter: "Завязки" },
      { id: Math.random(), nameFilter: "Крючки" },
      { id: Math.random(), nameFilter: "Кулиска" },
      { id: Math.random(), nameFilter: "Люверсы" },         
    ],
  },
];